# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: 'FaceDataset'
  params:
  inner_fold: 'valid'
  outer_fold: 'valid'
  data_dir: '../../data/dfdc/frame-mtcnn/'
  pickled: '../../data/dfdc/train_from_mtcnn_bbox_annotations_with_splits.pkl'
  sampler: 'GroupSampler'


transform:
  concat: False
  augment: 
    train: 'train_pipeline'
    infer: 'test_pipeline'
  num_workers: 0
  resize_to: [512, 512]
  preprocess:
    augmentations: 'vanilla_transforms'
    size_divisor: 128 # required for NAS-FPN/EfficientNet backbones
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  config: 'SSDVGG' 
  bbox_head:
    num_classes: 2   # remember to include background class
  train_cfg:
  test_cfg:
    nms:
      iou_thr: 0.1

find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1.0e-2
    num_iter: 500
    save_fig: True


train:
  batch_size: 16
  trainer: 'Trainer'
  params:
    gradient_accumulation: 1
    num_epochs: 10
    steps_per_epoch: 0
    validate_interval: 1
    verbosity: 100
    grad_clip: {'max_norm': 35, 'norm_type': 2}


evaluation:
  evaluator: 'Evaluator'
  params:
    save_checkpoint_dir: '../../checkpoints/detect/ssd_mtcnn/'
    save_best: True
    prefix: 'ssdvgg'
    metrics: ['overall_map', 'overall_map_50', 'overall_map_75']
    valid_metric: 'overall_map_50'
    mode: 'max'
    improve_thresh: 0.0001


optimizer:
  name: 'AdamW'
  params:
    lr: 1.2e-5
    weight_decay: 1.0e-4


scheduler:
  name: 'CustomOneCycleLR'
  params:
    max_lr:   3.0e-4
    final_lr: 1.0e-12
    pct_start: 0.3
    cycle_momentum: False


predict:
  checkpoint: '../../checkpoints/detect/dfdc/RET50_000_VM-0.9999.PTH'
  data_dir: '../../data/dfdc/frames/'
  pickled: '../../data/dfdc/abbrev_frames_annotations_for_widerface_retinanet.pkl'
  save_preds_dir: '../../data/dfdc/face_predictions_round2/'
  predictor: 'Predictor'
  params:
    predict_mode: True

