# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: 'FaceVideoDataset'
  params:
    max_frames: 8
  sampler:
    name: 'PartSampler'
  inner_fold: 'valid'
  outer_fold: 'valid'
  data_dir: '../data/dfdc/jph/videos/'
  csv_filename: '../data/dfdc/jph/train_video_with_splits.csv'


transform:
  augment: 'gentle_transform'
  probability: 0.75
  num_workers: 0
  pad_ratio: null
  resize_to: null # (256, 256)
  crop_to: [224, 224]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  name: 'RNNHead'
  params:
    num_classes: 1
    backbone: 'resnet50'
    dropout: 0.2
    pretrained: 'imagenet'
    rnn: 'gru'
    hidden_size: null


find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1
    num_iter: 500
    save_fig: True


train:
  outer_only: False
  batch_size: 10
  trainer: 'Trainer'
  params:
    gradient_accumulation: 1
    num_epochs: 20
    steps_per_epoch: 0
    validate_interval: 2
    verbosity: 100


evaluation:
  batch_size: 2
  evaluator: 'Evaluator'
  params:
    save_checkpoint_dir: '../checkpoints/skp/baseline/'
    save_best: True
    prefix: 'r34rnn'
    metrics: ['log_loss']
    valid_metric: 'log_loss'
    mode: 'min'
    improve_thresh: 0.001


loss:
  name: 'BCEWithLogitsLoss'
  params:


optimizer:
  name: 'AdamW'
  params:
    lr: 1.2e-5
    weight_decay: 5.0e-4


scheduler:
  name: 'CustomOneCycleLR'
  params:
    max_lr:   3.0e-4
    final_lr: 1.0e-12
    pct_start: 0.1
    anneal_strategy: 'linear'
    cycle_momentum: False


test:
  checkpoint: '.pth'
  batch_size: 128
  data_dir:
  save_preds_dir: 
  labels_available: 
  outer_only: True


predict:
  checkpoint: '.pth'
  batch_size: 128
  data_dir:
  save_preds_dir:
  outer_only: True
   