# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 88 

dataset:
  name: 'BengaliDataset'
  params:
  inner_fold: 0
  outer_fold: 0
  data_dir: '../data/train_images/'
  csv_filename: '../data/train_labels_with_splits.csv'


transform:
  augment: 'vanilla_transform'
  probability: 0.5
  num_workers: 0
  pad_ratio: 0.58051
  resize_to: [130, 224]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  name: 'TripleHead'
  params:
    num_classes: [168, 11, 7]
    backbone: 'efficientnet_b4'
    dropout: 0.2
    pretrained: 'imagenet'


find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1
    num_iter: 1000
    save_fig: True


train:
  outer_only: False
  batch_size: 16
  trainer: 'Trainer'
  params:
    gradient_accumulation: 4
    num_epochs: 10
    steps_per_epoch: 0
    validate_interval: 2
    verbosity: 10


evaluation:
  batch_size: 128
  evaluator: 'Evaluator'
  params:
    save_checkpoint_dir: '../checkpoints/sandbox/'
    save_best: True
    prefix: 'effb4'
    metrics: ['avg_recall']
    valid_metric: 'avg_recall'
    mode: 'max'
    improve_thresh: 0.001


loss:
  name: 'TripleCrossEntropy'
  params:


optimizer:
  name: 'AdamW'
  params:
    lr: 2.8e-5
    weight_decay: 5.0e-4


scheduler:
  name: 'CustomOneCycleLR'
  params:
    max_lr:   7.0e-4
    final_lr: 1.0e-12
    pct_start: 0.3
    anneal_strategy: 'linear'
    cycle_momentum: False


test:
  checkpoint: '.pth'
  batch_size: 128
  data_dir:
  save_preds_dir: 
  labels_available: 
  outer_only: True


predict:
  checkpoint: '.pth'
  batch_size: 128
  data_dir:
  save_preds_dir:
  outer_only: True
   